### ISSUE TITLE
Team 5414 Code Review

### ISSUE THREAD

**Issue by bryanyli** [chopshop-166/frc-2020#54]
### Vision
- One optimization I could find that could be beneficial is to preallocate memory for your image matrices (bgr, hsv, and binary) outside of the while loop, so that you aren't allocating approximately 2MB of memory multiple times per second, which should help increase the framerate.

### Robot
- Is there a reason why you chose to use inline commands for every command instead of having a commands folder for the more complicated ones? That should increase readability.
- Is there a reason why you chose not to use the new RobotContainer rather than putting everything in Robot.java?

Other than those few things, I think your robot code looks great.

**Comment by msoucy** [comment]
Thank you for your feedback!

- Would you happen to have more information on preallocating with Python? I found [a reference](https://answers.opencv.org/question/216101/read-image-to-an-already-allocated-mat/) but it appears to not have a good answer. It's definitely something that would be nice to do.
- We chose inline methods because we want the external interface for all subsystems, to be the command interface. While this does cause the subsystem to be longer, it also reduces the odds of the subsystem's rules being violated (things happening without being commanded). It's a discussion that we may reopen for more complex commands.
- We found the `RobotContainer` to not serve sufficient purpose for our needs at this time, given our use of maps as classes. After reconsidering based on your prompting, we have determined that the container setup may be useful for the map setup after all. It's something we're going to investigate, thank you.

**Comment by bryanyli** [comment]
Preallocating is just creating variables outside of the main loop. Basically, what you'd need to do is something like this:
```py
img = np.zeros((height, width, 3), dtype = np.uint8)
hsv_img = np.zeros((height, width, 3), dtype = np.uint8)
binary_img =  np.zeros((height, width, 3), dtype = np.uint8)
output_img =  np.zeros((height, width, 3), dtype = np.uint8)

while True:
  img = frame.get_data()
  hsv_img = cv2.cvtColor(...)
  etc.
```

However, for your `imgfilter` function, you have to add args for the preallocated matrices so that you can modify them within the function.

**Comment by msoucy** [comment]
In the example you give, you allocate memory - and then remove the reference to them when you assign a new value using `=`. I'd just like to make sure that that's clear. Using OpenCV currently, there doesn't appear to be a way to pass in a buffer to write into.

**Comment by bryanyli** [comment]
Having ran some benchmarks, it does seem like what you say is true. I've also tried with `np.copyto()` and `arr[:] = ...`, and all 4 methods time pretty similarly. Sorry for the misunderstanding, I assumed that the image would be read into the preallocated array rather than assigning a new array.

**Comment by msoucy** [comment]
No worries! In many situations it would definitely be good advice. The only reasons it isn't in this case, is that opencv doesn't provide a way to pass in a buffer for the output, and that Python uses reference variables.

For future readers:

What this means is that when you use `x = y`, you make x and y refer to the exact same object, not two identical objects. For things like integers, or things that can't be modified in place, that's fine. But if you do it in a list, it can have surprising behavior. `x = []; y = x; y.append(5); assert len(x) == 1` is correct, since `x` and `y` refer to the same list.

So in the example you gave above, opencv would construct a new buffer object, and then change `hsv_img` to reference that buffer object, instead of filling the existing buffer. The other methods you showed (`arr[:]` and `np.copyto`) should actually be slightly slower, since they still construct/allocate the new buffer, and then spend extra time copying the values into the existing buffer.
